FROM golang:1-alpine3.17 AS builder

RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev bash jq yq curl
WORKDIR /build

RUN go install github.com/mitranim/gow@latest

COPY go.mod go.sum /build/
COPY slackgo/ /build/slackgo/
RUN go mod download

COPY . /build
RUN go build -o /usr/bin/mautrix-slack

# Setup development stack using gow
RUN echo 'gow run /build $@' > /usr/bin/mautrix-slack \
    && chmod +x /usr/bin/mautrix-slack
VOLUME /data
